### PR TITLE
Add sticky footer

### PR DESCRIPTION
**Pull request by treetrnk**
I added a footer to the site that allows for the easy display of information about the group facilitator and people who have worked on the site. It also contains an icon pointing to the Github repository for the site and an icon pointing to the groups meetup page. 

If there is anything that you would like changed, such as the information displayed or background color, let me know and I would be happy to update it. Along the same lines, I couldn't remember Ryan's last name so I just wrote Ryan. I'd be fine with removing the Contributors line altogether though if its unnecessary.

### CODE REVIEW

**Comment by amayer5125** [comment]
I think all the names might be a little too much. Maybe we could just have "Check us out on: [github icon] [meetup icon]"
What do you think? I am trying to keep the look of the site really clean. And the organizer and co-organizers are all outlined on the meetup site.

**Comment by treetrnk** [comment]
Sounds good to me. I was just throwing out ideas. How does it look now?

**Comment by amayer5125** [comment]
That looks better. Less busy.
Can we make it a little shorter though. Maybe like 10-20px smaller? I think a couple pixles padding top and bottom would be good good but I think it just looks bulky at the bottom of the page.

**Comment by treetrnk** [comment]
Sure. How is that? Now it is 50px tall as opposed to the 75px that it previously was. Is it too short?

**Comment by amayer5125** [comment]
That looks perfect!
Just 2 more things and I will merge.
Can you move all the code you added into _inc/footer.php_. Then include footer.php above each _inc/scripts_bottom.php_ like:

``` php
<?php
require 'inc/footer.php';
require 'inc/scripts_bottom.php';
?>
```

Also instead of doing `<div id="footer>` lets html5 this sucker and use `<footer>`. Then just update `#footer {` to `footer {` and we should be good.

Sorry I keep coming back with changes. Just trying to keep the site and the code clean.

**Comment by treetrnk** [comment]
No problem. I was actually wondering whether or not you would want that separated out. Anyway, it's done now. Everything should be as you requested.

**Pull request merged**
